name: CI Kyberium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3-dev python3-pip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage flake8

      - name: Lint (flake8)
        run: |
          flake8 kyberium/ tests/

      - name: Run unit and integration tests
        run: |
          coverage run -m unittest discover -s tests

      - name: Report coverage
        run: |
          coverage report
          coverage xml
        continue-on-error: true

      - name: Build C++ bindings (pybind11)
        run: |
          sudo apt-get install -y pybind11-dev
          mkdir -p build && cd build
          cmake ..
          make
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Test C++ bindings import (optionnel)
        run: |
          python3 -c "import kyberium_cpp"
        working-directory: ${{ github.workspace }}/build
        continue-on-error: true

  # Optionnel : badge de statut, artefacts, etc. 